/**
 * Datadog API V1 Collection
 * Collection of all Datadog Public endpoints.
 *
 * OpenAPI spec version: 1.0
 * Contact: support@datadoghq.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { SLOCorrectionCreateRequestData } from "./SLOCorrectionCreateRequestData";
import { HttpFile } from "../http/http";

/**
 * An object that defines a correction to be applied to an SLO
 */
export class SLOCorrectionCreateRequest {
  "data"?: SLOCorrectionCreateRequestData;

  static readonly discriminator: string | undefined = undefined;

  static readonly attributeTypeMap: Array<{
    name: string;
    baseName: string;
    type: string;
    format: string;
  }> = [
    {
      name: "data",
      baseName: "data",
      type: "SLOCorrectionCreateRequestData",
      format: "",
    },
  ];

  static getAttributeTypeMap() {
    return SLOCorrectionCreateRequest.attributeTypeMap;
  }

  public constructor() {}
}
