/**
 * Unless explicitly stated otherwise all files in this repository are licensed under the Apache-2.0 License.
 * This product includes software developed at Datadog (https://www.datadoghq.com/).
 * Copyright 2020-Present Datadog, Inc.
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { SyntheticsCITestMetadataPipeline } from "./SyntheticsCITestMetadataPipeline";
import { SyntheticsCITestMetadataProvider } from "./SyntheticsCITestMetadataProvider";
import { ObjectSerializer } from "./ObjectSerializer";

/**
 * Describe CI metadata.
 */

export class SyntheticsCITestMetadataCI {
  "pipeline"?: SyntheticsCITestMetadataPipeline;
  "provider"?: SyntheticsCITestMetadataProvider;

  "unparsedObject"?: any;

  static readonly discriminator: string | undefined = undefined;

  static readonly attributeTypeMap: {
    [key: string]: { baseName: string; type: string; format: string };
  } = {
    pipeline: {
      baseName: "pipeline",
      type: "SyntheticsCITestMetadataPipeline",
      format: "",
    },
    provider: {
      baseName: "provider",
      type: "SyntheticsCITestMetadataProvider",
      format: "",
    },
  };

  static getAttributeTypeMap() {
    return SyntheticsCITestMetadataCI.attributeTypeMap;
  }

  static deserialize(data: { [key: string]: any }): SyntheticsCITestMetadataCI {
    const res = new SyntheticsCITestMetadataCI();

    res.pipeline = ObjectSerializer.deserialize(
      data.pipeline,
      "SyntheticsCITestMetadataPipeline",
      ""
    );

    res.provider = ObjectSerializer.deserialize(
      data.provider,
      "SyntheticsCITestMetadataProvider",
      ""
    );

    return res;
  }

  static serialize(data: SyntheticsCITestMetadataCI): { [key: string]: any } {
    const attributeTypes = SyntheticsCITestMetadataCI.getAttributeTypeMap();
    const res: { [index: string]: any } = {};
    for (const [key, value] of Object.entries(data)) {
      if (!(key in attributeTypes)) {
        throw new TypeError(`${key} attribute not in schema`);
      }
    }
    if (data?.unparsedObject !== undefined) {
      return data.unparsedObject;
    }
    res.pipeline = ObjectSerializer.serialize(
      data.pipeline,
      "SyntheticsCITestMetadataPipeline",
      ""
    );

    res.provider = ObjectSerializer.serialize(
      data.provider,
      "SyntheticsCITestMetadataProvider",
      ""
    );

    return res;
  }

  public constructor() {}
}
