/**
 * Datadog API V1 Collection
 * Collection of all Datadog Public endpoints.
 *
 * OpenAPI spec version: 1.0
 * Contact: support@datadoghq.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { TimeSeriesFormulaAndFunctionEventQueryDefinitionSort } from "./TimeSeriesFormulaAndFunctionEventQueryDefinitionSort";
import { HttpFile } from "../http/http";

/**
 * List of objects used to group by.
 */
export class TimeSeriesFormulaAndFunctionEventQueryDefinitionGroupBy {
  /**
   * Event facet.
   */
  "facet": string;
  /**
   * Number of groups to return.
   */
  "limit"?: number;
  "sort"?: TimeSeriesFormulaAndFunctionEventQueryDefinitionSort;

  static readonly discriminator: string | undefined = undefined;

  static readonly attributeTypeMap: Array<{
    name: string;
    baseName: string;
    type: string;
    format: string;
  }> = [
    {
      name: "facet",
      baseName: "facet",
      type: "string",
      format: "",
    },
    {
      name: "limit",
      baseName: "limit",
      type: "number",
      format: "int64",
    },
    {
      name: "sort",
      baseName: "sort",
      type: "TimeSeriesFormulaAndFunctionEventQueryDefinitionSort",
      format: "",
    },
  ];

  static getAttributeTypeMap() {
    return TimeSeriesFormulaAndFunctionEventQueryDefinitionGroupBy.attributeTypeMap;
  }

  public constructor() {}
}
