/**
 * Datadog API V1 Collection
 * Collection of all Datadog Public endpoints.
 *
 * OpenAPI spec version: 1.0
 * Contact: support@datadoghq.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { FormulaAndFunctionEventAggregation } from "./FormulaAndFunctionEventAggregation";
import { FormulaAndFunctionEventsSortType } from "./FormulaAndFunctionEventsSortType";
import { QuerySortOrder } from "./QuerySortOrder";
import { HttpFile } from "../http/http";

/**
 * Options for sorting group by results.
 */
export class TimeSeriesFormulaAndFunctionEventQueryDefinitionGroupBySort {
  "aggregation": FormulaAndFunctionEventAggregation;
  /**
   * Metric used for sorting group by results.
   */
  "metric"?: string;
  "order"?: QuerySortOrder;
  "type"?: FormulaAndFunctionEventsSortType;

  static readonly discriminator: string | undefined = undefined;

  static readonly attributeTypeMap: Array<{
    name: string;
    baseName: string;
    type: string;
    format: string;
  }> = [
    {
      name: "aggregation",
      baseName: "aggregation",
      type: "FormulaAndFunctionEventAggregation",
      format: "",
    },
    {
      name: "metric",
      baseName: "metric",
      type: "string",
      format: "",
    },
    {
      name: "order",
      baseName: "order",
      type: "QuerySortOrder",
      format: "",
    },
    {
      name: "type",
      baseName: "type",
      type: "FormulaAndFunctionEventsSortType",
      format: "",
    },
  ];

  static getAttributeTypeMap() {
    return TimeSeriesFormulaAndFunctionEventQueryDefinitionGroupBySort.attributeTypeMap;
  }

  public constructor() {}
}
