/**
 * Datadog API V1 Collection
 * Collection of all Datadog Public endpoints.
 *
 * OpenAPI spec version: 1.0
 * Contact: support@datadoghq.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { AWSTagFilterListResponseFilters } from './AWSTagFilterListResponseFilters';
import { HttpFile } from '../http/http';

/**
* An array of tag filter rules by `namespace` and tag filter string.
*/
export class AWSTagFilterListResponse {
    /**
    * An array of tag filters.
    */
    'filters'?: Array<AWSTagFilterListResponseFilters>;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "filters",
            "baseName": "filters",
            "type": "Array<AWSTagFilterListResponseFilters>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return AWSTagFilterListResponse.attributeTypeMap;
    }
    
    public constructor() {
    }
}

