/**
 * Datadog API V1 Collection
 * Collection of all Datadog Public endpoints.
 *
 * OpenAPI spec version: 1.0
 * Contact: support@datadoghq.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { SLOCorrectionUpdateRequestAttributes } from "./SLOCorrectionUpdateRequestAttributes";
import { HttpFile } from "../http/http";

/**
 * The data object associated with the SLO correction to be updated
 */
export class SLOCorrectionUpdateRequestData {
  "attributes"?: SLOCorrectionUpdateRequestAttributes;
  /**
   * Should always be set to \"correction\"
   */
  "type"?: string;

  static readonly discriminator: string | undefined = undefined;

  static readonly attributeTypeMap: Array<{
    name: string;
    baseName: string;
    type: string;
    format: string;
  }> = [
    {
      name: "attributes",
      baseName: "attributes",
      type: "SLOCorrectionUpdateRequestAttributes",
      format: "",
    },
    {
      name: "type",
      baseName: "type",
      type: "string",
      format: "",
    },
  ];

  static getAttributeTypeMap() {
    return SLOCorrectionUpdateRequestData.attributeTypeMap;
  }

  public constructor() {}
}
