/**
 * Datadog API V1 Collection
 * Collection of all Datadog Public endpoints.
 *
 * OpenAPI spec version: 1.0
 * Contact: support@datadoghq.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { SLOCorrectionResponseAttributes } from "./SLOCorrectionResponseAttributes";
import { HttpFile } from "../http/http";

/**
 * The data object associated with the SLO correction
 */
export class SLOCorrectionResponseData {
  "attributes"?: SLOCorrectionResponseAttributes;
  /**
   * The ID of the SLO correction
   */
  "id"?: string;
  /**
   * Should always return \"correction\"
   */
  "type"?: string;

  static readonly discriminator: string | undefined = undefined;

  static readonly attributeTypeMap: Array<{
    name: string;
    baseName: string;
    type: string;
    format: string;
  }> = [
    {
      name: "attributes",
      baseName: "attributes",
      type: "SLOCorrectionResponseAttributes",
      format: "",
    },
    {
      name: "id",
      baseName: "id",
      type: "string",
      format: "",
    },
    {
      name: "type",
      baseName: "type",
      type: "string",
      format: "",
    },
  ];

  static getAttributeTypeMap() {
    return SLOCorrectionResponseData.attributeTypeMap;
  }

  public constructor() {}
}
