/**
 * Datadog API V1 Collection
 * Collection of all Datadog Public endpoints.
 *
 * OpenAPI spec version: 1.0
 * Contact: support@datadoghq.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

/**
* Query metadata.
*/
export class SLOHistoryMetricsSeriesMetadata {
    /**
    * Query aggregator function.
    */
    'aggr'?: string;
    /**
    * Query expression.
    */
    'expression'?: string;
    /**
    * Query metric used.
    */
    'metric'?: string;
    /**
    * Query index from original combined query.
    */
    'queryIndex'?: number;
    /**
    * Query scope.
    */
    'scope'?: string;
    /**
    * Query units (if available).
    */
    'unit'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "aggr",
            "baseName": "aggr",
            "type": "string",
            "format": ""
        },
        {
            "name": "expression",
            "baseName": "expression",
            "type": "string",
            "format": ""
        },
        {
            "name": "metric",
            "baseName": "metric",
            "type": "string",
            "format": ""
        },
        {
            "name": "queryIndex",
            "baseName": "query_index",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "scope",
            "baseName": "scope",
            "type": "string",
            "format": ""
        },
        {
            "name": "unit",
            "baseName": "unit",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return SLOHistoryMetricsSeriesMetadata.attributeTypeMap;
    }
    
    public constructor() {
    }
}

